### ISSUE TITLE
day 3 node and day 3 deno correctness issue

### ISSUE THREAD

**Issue by jeff-hykin** [Starwort/advent-of-code-golf-2024#1]
Incorrect submissions; last two accepted node submissions by `rucin93`, and the most recent deno day 3 submission by me (by accident) `jeff.hykin ` on discord.

Last known correct solution day 3 node was by `tree(dmrichwa)` (131 bytes) and last correct deno day 3 submission was my prior one:
```js
new Response(Deno.stdin.readable).text().then((a,c=0,s=0,t=0,d=0,f=a.replace(/mul\((\d+),(\d+)\)|do(n't)?/g,(_,a,b,e)=>a?(s+=t=a*b,c+=t*!d):d=e))=>console.log(s,c))
```

Counter example showing incorrectness is to include `Xul(9,1?)` in the input, and/or `don_mul(1,3)`

**Comment by Starwort** [comment]
Contacted individually on Discord - for future queries, Discord is the easiest way to contact me (I'm available in the Code.Golf server, just ping me in the AoC channel).

I'll leave this issue open until we've resolved this

**Comment by jeff-hykin** [comment]
Oh sorry about that, we did discuss on discord a while ago and its resolved, at least for me.

The conclusion was roughly "brittleness is accepted, so long as it passes all the AOC inputs (the ones from all different users). Even if the submitted solution doesnt match the theoretical solution, that's fine". So all the submitted ones I mentioned here were actually fine as-is.

While that policy surprised me, the other players seemed to be in agreement, and I dont have any problem with it so long as everyone is on the same page.
